### ISSUE TITLE
gulp-nittro: repeat use

### ISSUE THREAD

**Issue by webrouse** [nittro/nittro#17]
Hi,

I really like the Nittro and I use it in projects with the `gulp-nittro` package.

I have encountered a problem when I want to REPEAT USE builder or configuration object.

**Example 1**
*gulpfile.babel.js*:
```js
import gulp from 'gulp';
import concat from 'gulp-concat';
import nittro from 'gulp-nittro';
import merge from 'merge2';
import size from 'gulp-size';

gulp.task('default', () => {
  const nittroConfig = {
    base: {
      core: true,
      datetime: false,
      neon: false,
      di: true,
      ajax: true,
      forms: true,
      page: true,
      flashes: true,
      routing: true,
    },
    extras: {
      checklist: false,
      dialogs: false,
      confirm: false,
      dropzone: false,
      paginator: false,
      keymap: false,
      storage: false,
    },
    bootstrap: false,
    stack: false,
  };

  const stream1 = nittro('js', new nittro.Builder(nittroConfig)) // <------------
    .pipe(concat('nittro1.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  const stream2 = nittro('js', new nittro.Builder(nittroConfig)) // <------------
    .pipe(concat('nittro2.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  return merge(stream1, stream2);
});
```
*output*:
```
[09:10:08] Requiring external module babel-register
[09:10:09] Using gulpfile ~/Projects/github/n-sandbox/gulpfile.babel.js
[09:10:09] Starting 'default'...
[09:10:09] 'default' errored after 13 ms
[09:10:09] Error: Cannot find module 'nittro-nittro-core/package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at resolvePath (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:57:24)
    at readPackageMeta (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:117:55)
    at getDependencies (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:92:16)
    at addPackageWithDependencies (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:77:24)
    at /home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:67:17
    at Array.forEach (native)
    at buildPackageList (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:64:20)
    at new Builder (/home/user/Projects/github/n-sandbox/node_modules/nittro/index.js:285:23)
[09:10:09] nittro1.js 275.92 kB
```
*problem*: The second stream `stream2` is not working.

*reason*: Probably the side effects over the `nittroConfig`.

**Example 2**

*gulpfile.babel.js*:
```js
import gulp from 'gulp';
import concat from 'gulp-concat';
import nittro from 'gulp-nittro';
import merge from 'merge2';
import size from 'gulp-size';

gulp.task('default', () => {
  const nittroConfig = {
    base: {
      core: true,
      datetime: false,
      neon: false,
      di: true,
      ajax: true,
      forms: true,
      page: true,
      flashes: true,
      routing: true,
    },
    extras: {
      checklist: false,
      dialogs: false,
      confirm: false,
      dropzone: false,
      paginator: false,
      keymap: false,
      storage: false,
    },
    bootstrap: false,
    stack: false,
  };

  const nittroBuilder = new nittro.Builder(nittroConfig);

  const stream1 = nittro('js', nittroBuilder) // <------------
    .pipe(concat('nittro1.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  const stream2 = nittro('js', nittroBuilder) // <------------
    .pipe(concat('nittro2.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  return merge(stream1, stream2);
});
```

*output*:
```
[09:11:12] Requiring external module babel-register
[09:11:12] Using gulpfile ~/Projects/github/n-sandbox/gulpfile.babel.js
[09:11:12] Starting 'default'...
[09:11:12] nittro1.js 114.83 kB
[09:11:12] nittro2.js 161.09 kB
[09:11:12] Finished 'default' after 37 ms
```
*problem*: Nittro is divided between `stream1` and `stream2`.

*reason*: I do not know, but the above code at first glance does not look wrong.

**Example 3**

*gulpfile.babel.js*:
```js
import gulp from 'gulp';
import concat from 'gulp-concat';
import nittro from 'gulp-nittro';
import merge from 'merge2';
import size from 'gulp-size';

gulp.task('default', () => {
  const nittroConfig = {
    base: {
      core: true,
      datetime: false,
      neon: false,
      di: true,
      ajax: true,
      forms: true,
      page: true,
      flashes: true,
      routing: true,
    },
    extras: {
      checklist: false,
      dialogs: false,
      confirm: false,
      dropzone: false,
      paginator: false,
      keymap: false,
      storage: false,
    },
    bootstrap: false,
    stack: false,
  };

  const nittroFactory = () => nittro('js', new nittro.Builder(Object.assign({}, nittroConfig)));

  const stream1 = nittroFactory()  // <------------
    .pipe(concat('nittro1.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  const stream2 = nittroFactory()  // <------------
    .pipe(concat('nittro2.js'))
    .pipe(size({ showFiles: true, showTotal: false }));

  return merge(stream1, stream2);
});
```

*output*:
```
[09:21:05] Requiring external module babel-register
[09:21:05] Using gulpfile ~/Projects/github/n-sandbox/gulpfile.babel.js
[09:21:05] Starting 'default'...
[09:21:05] nittro1.js 275.92 kB
[09:21:05] nittro2.js 275.92 kB
[09:21:05] Finished 'default' after 48 ms
```
*This works.*

**Summary**

It may seem like marginal cases but I use Nittro in the project along with `gulp.watch` and the compilation will only work properly for the first time. I compile all scripts to one file. Certainly, this could be bypassed by using some kind of caching (to run the nittro compilation only once). But that would unnecessarily increase the complexity of the solution.

Mentioned problems may discourage new users who are not experts in JavaScript.

Thank you.

**Comment by teekey99** [comment]
@webrouse I have encountered similar difficulties while using `gulp.watch` and I don't see anything wrong on having your config object as a return value of a function that is called every time you need to compiled your scripts.

```javascript
const makeConfig = () => {
  base: {
    core: true,
    datetime: false,
    neon: false,
    di: true,
    ajax: true,
    forms: true,
    page: true,
    flashes: true,
    routing: true,
  },
  extras: {
    checklist: false,
    dialogs: false,
    confirm: false,
    dropzone: false,
    paginator: false,
    keymap: false,
    storage: false,
  },
    bootstrap: false,
    stack: false,
}

gulp.watch('/path/to/scripts/**.js', () => {
  const config = makeConfig();
  return nittro('js', config)
    .pipe(concat('bundle.js'))
    .pipe(gulp.dest('/path/to/destination');
});
```

This is a just a quick example, but a very similar approach works for me well, though I keep my `makeConfig` functions in separate files for each module of my project and require them into a single `nittroConfig` object from which I call them when and where I need them.

```javascript
const nittroConfig = {
  admin: require('./nittro.admin.config'),
  front: require('./nittro.front.config'),
}

gulp.task('nittro-front', () => {
 const config = nittroConfig['front'](); 
 return nittro('js', config).
   .pipe(concat('front.js'))
   .pipe(gulp.dest('./'));
});
```

Again, this is just a simplified example, I actually create all `nittro` tasks dynamically according to my modules mapping.

**Comment by jahudka** [comment]
Hi, sorry for not getting back to you sooner, I was out of town & offline for most of August. This indeed is a bug - side effects of processing the supplied configuration object shouldn't affect other code. I've just published version 2.0.19 of the `nittro` package which should fix this, try updating with `npm i nittro` - all three examples you posted work for me after the update.

**Comment by jahudka** [comment]
No feedback -> closing. Plus as I said the issue should be fixed.

**Comment by webrouse** [comment]
Sorry. Yes, everything is fine.
